chatbotproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('musicbot/', include('musicbot.urls')),
    path('admin/', admin.site.urls),
]

musicbot/urls.py
from django.urls import path
from .views import MusicBotView, SongListView

urlpatterns = [
    # Secret webhook url
    path('05f129f85fbad4fd4223a922f011f550e3b4c3ab14ddee6588/', MusicBotView.as_view()),
    path('songlistview/<str:fav>/<str:sender_id>/', SongListView.as_view()),
]

musicbot/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from enum import Enum

class PayloadEnum(Enum):
    WELCOME = 0
    SEARCH_LYRICS = 1
    SHOW_REPORTS = 2
    
    FAV_LIST = 3
    NO_FAV_LIST = 4
    EMPTY = 5

    SONG_SELECTED = 6
    FAV_SONG_SELECTED = 7
    
    SAVE_FAV = 8
    NO_SAVE_FAV = 9


class StateEnum(Enum):
    WELCOME = 0
    MENU_OPTIONS = 1
    MENU_FAV_LIST = 2
    MENU_LYRICS = 3
    FAV_SONGS = 4
    ASK_SONG_QUERY = 5

    SONG_SELECTED = 6

    MENU_SAVE_FAV = 7




class Conversation(TimeStampedModel):
    fb_user_id = models.CharField(max_length=100)
    state = models.CharField(max_length=1,
                             choices=[(tag.name, tag.value)
                                       for tag in StateEnum],
                             )

    class Meta:
        ordering = ['-created']


class Message(TimeStampedModel):
    conversation = models.ForeignKey("Conversation", on_delete=models.CASCADE)

    text = models.CharField(max_length=500,
                            blank=True,
                            null=True,
                            )

    payload = models.CharField(max_length=100,
                               blank=True,
                               null=True,
                               )
                                
    class Meta:
        ordering = ['-created']


class Track(models.Model):
    conversation = models.ForeignKey("Conversation", on_delete=models.CASCADE)
    track_id = models.CharField(max_length=100)

musicbot/forms.py
from django import forms

class TrackForm(forms.Form):
    sender_id = forms.CharField(max_length=100,
                                widget=forms.HiddenInput())

    track_id = forms.CharField(max_length=100,
                               widget=forms.HiddenInput())

musicbot/views.py
from django.views import generic
from django.views.generic.edit import FormMixin
from django.http.response import HttpResponse
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from .models import Message, Conversation, StateEnum, Track, PayloadEnum
from .forms import TrackForm
from .musixmatch import search_track
from .musixmatch import get_track
from . import musixmatch
import json
from .facebook import (MessageHandler,
                       TextResponse,
                       NamedTextResponse,
                       QuickResponse,
                       ResponseCollection,
                       ReportResponseCollection,
                       WebviewResponse,
                       IdWebviewResponse,
                       SaveSongMessageHandler,
                       )

# StateEnum.WELCOME
welcomeMH = MessageHandler()
welcomeMH.set_response(
        PayloadEnum.WELCOME.name,
        ResponseCollection([
            NamedTextResponse("Hola {name} :) Bienvenido a Musixbot!"),
            QuickResponse("Que deseas hacer?", [
                ("Buscar canciones", PayloadEnum.SEARCH_LYRICS.name),
                ("Ver reportes", PayloadEnum.SHOW_REPORTS.name)
            ]),
        ]),
        StateEnum.MENU_OPTIONS.name)

# StateEnum.MENU_OPTIONS
menuOptionsMH = MessageHandler()
menuOptionsMH.set_response(
        PayloadEnum.SEARCH_LYRICS.name,
        QuickResponse("Ver lista de favoritos?",[
            ("Si", PayloadEnum.FAV_LIST.name),
            ("No", PayloadEnum.NO_FAV_LIST.name)
        ]),
        StateEnum.MENU_FAV_LIST.name)

menuOptionsMH.set_response(
        PayloadEnum.SHOW_REPORTS.name,
        ReportResponseCollection([
            TextResponse("Total de usuarios: {number}"),
            TextResponse("Nuevos usuarios esta semana: {number}"),
            TextResponse("Búsquedas en la semana: {number}"),
            QuickResponse("Que deseas hacer?", [
                ("Buscar canciones", PayloadEnum.SEARCH_LYRICS.name),
                ("Ver reportes", PayloadEnum.SHOW_REPORTS.name)
            ]),
        ]),
        StateEnum.MENU_OPTIONS.name)

# StateEnum.MENU_FAV_LIST
menuFavListMH = MessageHandler()
menuFavListMH.set_response(
        PayloadEnum.FAV_LIST.name,
        IdWebviewResponse(
            "Seleccione una canción.",
            "Ver canciones",
            "https://still-ravine-89797.herokuapp.com/musicbot/songlistview/fav/{sender_id}/",
            "tall"),
        StateEnum.SONG_SELECTED.name)

menuFavListMH.set_response(
        PayloadEnum.NO_FAV_LIST.name,
        ResponseCollection([
            TextResponse("Hora de buscar una canción!"),
            TextResponse("Dime el nombre de la canción o del artista"),
            TextResponse("Si recuerdas algunas palabras de la canción también puedes indicarla"),
        ]),
        StateEnum.ASK_SONG_QUERY.name)


# StateEnum.ASK_SONG_QUERY
askSongQueryMH = MessageHandler()
askSongQueryMH.set_response(
        PayloadEnum.EMPTY.name,
        IdWebviewResponse(
            "Seleccione una canción.",
            "Ver canciones",
            "https://still-ravine-89797.herokuapp.com/musicbot/songlistview/nofav/{sender_id}",
            "tall"),
        StateEnum.SONG_SELECTED.name)

# StateEnum.SONG_SELECTED
selectedSongMH = MessageHandler()
selectedSongMH.set_response(
        PayloadEnum.SONG_SELECTED.name,
        ResponseCollection([
            TextResponse("lyrics"),
            QuickResponse("Guardar la canción en la lista de favoritos?", [
                ("Si", PayloadEnum.SAVE_FAV.name),
                ("No", PayloadEnum.NO_SAVE_FAV.name),
            ]),
        ]),
        StateEnum.MENU_SAVE_FAV.name)

selectedSongMH.set_response(
        PayloadEnum.FAV_SONG_SELECTED.name,
        ResponseCollection([
            TextResponse("lyrics"),
            QuickResponse("Que deseas hacer?", [
                ("Buscar canciones", PayloadEnum.SEARCH_LYRICS.name),
                ("Ver reportes", PayloadEnum.SHOW_REPORTS.name)
            ]),
        ]),
        StateEnum.MENU_OPTIONS.name)

menuSaveFavMH = SaveSongMessageHandler()
menuSaveFavMH.set_response(
        PayloadEnum.SAVE_FAV.name,
        ResponseCollection([
            TextResponse("Listo!"),
            QuickResponse("Que deseas hacer?", [
                ("Buscar canciones", PayloadEnum.SEARCH_LYRICS.name),
                ("Ver reportes", PayloadEnum.SHOW_REPORTS.name)
            ]),
        ]),
        StateEnum.MENU_OPTIONS.name)

menuSaveFavMH.set_response(
        PayloadEnum.NO_SAVE_FAV.name,
        QuickResponse("Que deseas hacer?", [
            ("Buscar canciones", PayloadEnum.SEARCH_LYRICS.name),
            ("Ver reportes", PayloadEnum.SHOW_REPORTS.name)
        ]),
        StateEnum.MENU_OPTIONS.name)

MH = {}
MH[StateEnum.WELCOME.name] = welcomeMH
MH[StateEnum.MENU_OPTIONS.name] = menuOptionsMH
MH[StateEnum.MENU_FAV_LIST.name] = menuFavListMH
MH[StateEnum.ASK_SONG_QUERY.name] = askSongQueryMH
MH[StateEnum.SONG_SELECTED.name] = selectedSongMH
MH[StateEnum.MENU_SAVE_FAV.name] = menuSaveFavMH



class MusicBotView(generic.View):
    def get(self, request, *args, **kwargs):
        if self.request.GET['hub.verify_token'] == "8246":   # Webhook Token
            return HttpResponse(self.request.GET['hub.challenge'])
        else:
            return HttpResponse("Error, invalid token")

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return generic.View.dispatch(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        incoming_message = json.loads(self.request.body.decode('utf-8'))

        # Facebook recommends going through every entry since they might send
        # multiple messages in a single call during high load
        for entry in incoming_message['entry']:
            for message in entry['messaging']:
                sender_id = message['sender']['id']
                text = ""
                payload = PayloadEnum.EMPTY.name

                if 'postback' in message:
                    payload = message['postback']['payload']
                    text = message['postback']['title']

                elif 'message' in message:
                    text = message['message']['text']

                    if "quick_reply" in message['message']:
                        payload = message['message']['quick_reply']['payload']

                if text:
                    print("Text: ", text)
                    print("Payload: ", payload)
                    try:
                        c = Conversation.objects.get(fb_user_id=sender_id)
                    except Conversation.DoesNotExist:
                        c = Conversation.objects.create(
                                fb_user_id=sender_id,
                                state=StateEnum.WELCOME.name)

                    print("State: ", c.state)
                    print(MH[c.state])
                    MH[c.state].handle_message(text, payload, c)

        return HttpResponse()


class SongListView(generic.ListView,
                   generic.edit.FormMixin,
                   generic.edit.ProcessFormView):

    template_name = "track_list.html"
    form_class = TrackForm
    success_url = "."

    def get_queryset(self):
        sender_id = self.kwargs['sender_id']
        query_type = self.kwargs['fav']

        if query_type == "fav":
            c = Conversation.objects.get(fb_user_id = sender_id)
            tracks = Track.objects.filter(conversation=c)

            track_list = [get_track(track.track_id)
                          for track in tracks]
        else:
            last_msg = Message.objects.all()[:1].get()
            track_list = musixmatch.search_track(last_msg.text)

        return track_list[:5]

    @method_decorator(xframe_options_exempt)
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        sender_id = form.cleaned_data['sender_id']
        track_id = form.cleaned_data['track_id']

        query_type = self.kwargs['fav']
        if query_type == "fav":
            payload = PayloadEnum.FAV_SONG_SELECTED.name
        else:
            payload = PayloadEnum.SONG_SELECTED.name

        lyrics = musixmatch.get_lyrics(track_id)

        c = Conversation.objects.get(fb_user_id=sender_id)

        # Check vs LyricsTextResponse with conversation query
        #  and lyrics by last message
        MH[c.state].responses[payload][0].responses[0].response_text = lyrics

        # Simulate a Messenger message
        MH[c.state].handle_message(track_id, payload, c)

        return super(SongListView, self).form_valid(form)

musicbot/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      html, body {
        height: 80%;
        display: grid;
      }
      
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif;
        font-weight: 400;
        -webkit-font-smoothing: antialiased;
        color: #222;
      }
      
      .cntr {
        margin-top: 30px;
        margin-left: 30px;
        font-size: 30px;
      }
      
      .btn-radio {
        cursor: pointer;
        display: inline-block;
        float: left;
        -webkit-user-select: none;
        user-select: none;
      }
      .btn-radio:not(:first-child) {
        margin-left: 20px;
      }
      @media screen and (max-width: 480px) {
        .btn-radio {
          display: block;
          float: none;
        }
        .btn-radio:not(:first-child) {
          margin-left: 0;
          margin-top: 15px;
        }
      }
      .btn-radio svg {
        fill: none;
        vertical-align: middle;
      }
      .btn-radio svg circle {
        stroke-width: 2;
        stroke: #C8CCD4;
      }
      .btn-radio svg path {
        stroke: #008FFF;
      }
      .btn-radio svg path.inner {
        stroke-width: 6;
        stroke-dasharray: 19;
        stroke-dashoffset: 19;
      }
      .btn-radio svg path.outer {
        stroke-width: 2;
        stroke-dasharray: 57;
        stroke-dashoffset: 57;
      }
      .btn-radio input {
        display: none;
      }
      .btn-radio input:checked + svg path {
        transition: all 0.4s ease;
      }
      .btn-radio input:checked + svg path.inner {
        stroke-dashoffset: 38;
        transition-delay: 0.3s;
      }
      .btn-radio input:checked + svg path.outer {
        stroke-dashoffset: 0;
      }
      .btn-radio span {
        display: inline-block;
        vertical-align: middle;
      }
    </style>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>

musicbot/templates/track_list.html
{% extends "base.html" %}
{% block body %}

<form class="form" id="trackForm" method="post">
  {{ form.as_p }}
    {% for track in object_list %}
    <div class="cntr">
      <label for="rdo-{{ forloop.counter }}" class="btn-radio">
        <input type="radio" id="rdo-{{ forloop.counter }}" name="radio-grp"
               value={{ track.track_id }}>
        <svg width="20px" height="20px" viewBox="0 0 20 20">
          <circle cx="10" cy="10" r="9"></circle>
          <path d="M10,7 C8.34314575,7 7,8.34314575 7,10 C7,11.6568542 8.34314575,13 10,13 C11.6568542,13 13,11.6568542 13,10 C13,8.34314575 11.6568542,7 10,7 Z" class="inner"></path>
          <path d="M10,1 L10,1 L10,1 C14.9705627,1 19,5.02943725 19,10 L19,10 L19,10 C19,14.9705627 14.9705627,19 10,19 L10,19 L10,19 C5.02943725,19 1,14.9705627 1,10 L1,10 L1,10 C1,5.02943725 5.02943725,1 10,1 L10,1 Z" class="outer"></path>
        </svg>
        <span>{{ track.track_name  }}</span>
      </label>
    </div>
    {% endfor %}
    <input type="submit" value="Aceptar">
</form>

  <script>
    (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/messenger.Extensions.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'Messenger'));
  </script>

  <!-- Jquery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <!-- Set radiobuttons to form field -->
  <script>
    $('input[name="radio-grp"]').change(function(){
      $("#id_track_id").val($(this).val());
    });
    $("#id_sender_id").val( {{ view.kwargs.sender_id }} );
  </script>

  <script>
    window.extAsyncInit = function() {
      console.log('Messenger extensions are ready');

      var APP_ID = '1980550775299550';
      // handle button click
      $('#trackForm').submit(function(){
        console.log('Submit pressed');

        MessengerExtensions.requestCloseBrowser(function() {
          console.log("Window will be closed");
        }, function(error) {
          console.log("Error in MessengerExtensions");
          console.log(error);
        });
      });
    }
  </script>

{% endblock %}